# Generated by Django 5.0.4 on 2024-05-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_blooduser_options_alter_blooduser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooduser',
            name='blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bloodtype'),
        ),
        migrations.AlterField(
            model_name='blooduser',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blooduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
